services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - //home/julian/Projekte/homeassistant-deployment/running_instance:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - "8123:8123"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/bus/usb/001/002:/dev/ttyBT